## Cities
module Cities
  puts ">>>>>>>> Seeding Cities"
  cities = [
    "Abbaspur",                                                                               
    "Abbotabad",                                                                              
    "Afghan",                                                                                 
    "Ahmad Pur Lamma",                                                                        
    "Ahmed Pur Sial",                                                                         
    "Aroop Town",                                                                             
    "Athara Hazari",                                                                          
    "Attock",                                                                                 
    "Awaran",                                                                                 
    "Badin",                                                                                  
    "Bagh",                                                                                   
    "Bahawalnagar",                                                                           
    "Bahawalpur",                                                                             
    "Bajaur",
    "Bannu",
    "Barnala",
    "Battagram",
    "Bhakar",
    "Bhimber",
    "Bin Qasim",
    "Bunair",
    "Chaghi",
    "Chak Jhumra",
    "Chakwal",
    "Charsadda",
    "Chichawatni",
    "Chiniot",
    "Chishtian",
    "Chok Azam",
    "Dadu",
    "Dadyal",
    "Daharki",
    "Dalbandin",
    "Depal Pur",
    "Dera Ghazi Khan",
    "D-I Khan",
    "Digri",
    "Dir Lower",
    "Dir Upper",
    "Faisalabad",
    "Fateh Jang",
    "Fateh Pur",
    "Ferozwala",
    "Fort Abbas",
    "Gilgit",
    "Gojra",
    "Gujranwala",
    "Gujrat",
    "Gulabad",
    "Hadali",
    "Hafizabad",
    "Hala",
    "Haripur",
    "Haroonabad",
    "Hassan Abdal",
    "Haveli",
    "Hazara",
    "Hazro",
    "Hyderabad",
    "Islamabad",
    "Jahanian",
    "Jand",
    "Jaranwala",
    "Jhang",
    "Jhelum",
    "Kabirwala",
    "Kamalia",
    "Kamoke",
    "Karachi",
    "Karak",
    "Kasur",
    "Khairpur City",
    "Khan Pur",
    "Khanewal",
    "Khari Shareef",
    "Kharian",
    "Khiali Shah Pur Town",
    "Khoski",
    "Khushab",
    "Khyber Agency",
    "Kot Sultan",
    "Kotla",
    "Kotli",
    "Lahore",
    "Lakki Marwat",
    "Layyah",
    "Layyari",
    "Liaqat Pur",
    "Lodhran",
    "Mailsi",
    "Malakand",
    "Mansehra",
    "Mardan",
    "Mian Channu",
    "Mianwali",
    "Mir Ali",
    "Mirpur",
    "Mirpur Mathelo",
    "Mirpurkhas City",
    "Mitha Tawana",
    "Multan",
    "Murree",
    "Muzaffarabad",
    "Nandi Pur Town",
    "Narowal",
    "Nawabshah",
    "Neelum",
    "North Waziristan Agency",
    "Noshki",
    "Nowshera",
    "Okara",
    "Peshawar",
    "Pindi Gheb",
    "Qila Didar Singh Town",
    "Quaidabad",
    "Quetta",
    "Rahim Yar Khan",
    "Rawalpindi",
    "Renala Khurd",
    "Sadiqabad",
    "Saeedabad",
    "Sahiwal",
    "Samundri",
    "Sanghar",
    "Sargodha",
    "Sawabi",
    "Sharda",
    "Sheikhupura",
    "Shikarpur City",
    "Shorkot",
    "Sialkot",
    "Sukkur City",
    "Swat",
    "Talhar",
    "Tandlianwala",
    "Tando Adam",
    "Tando Allah Yar",
    "Tando Muhammad Khan",
    "Tandojam",
    "Tank",
    "Taxila",
    "Timergara",
    "Toba Tek Singh",
    "Umerkot",
    "Vehari",
    "Wazirabad",
    "Ubauro",
    "Matiari",
    "Ghotki",
    "Sudhnoti",
    "Mohmand",
    "Tando Jan Muhammad"
  ]
 
  City.delete_all
  ActiveRecord::Base.connection.execute("ALTER SEQUENCE cities_id_seq RESTART WITH 1")
  cities.each do |city|
    City.create(name: city)
  end
end